version: "3.7"

services:
  # DATABASE
  db:
    image: postgres:14.3
    container_name: db
    restart: always
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wedding
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 10

  # API
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3000:80
    external_links:
      - db
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wedding
