FROM node:16.15.1

ENV NODE_ENV=development

WORKDIR /app

COPY ["package.json", "package-lock.json*", "tsconfig.json", "./"]

COPY . .

RUN ls -a && npm install

EXPOSE 8080

# Run all new migrations on startup. 
# TODO: Normally this should not wipe the db but needs verifying
CMD ["npm run migrate:dev"]

ENTRYPOINT ["npm", "run", "dev"]
