version: "3.7"

services:
  # DATABASE
  # https://hub.docker.com/_/postgres
  db:
    container_name: db
    image: db

  # API
  api:
    container_name: api
    external_links:
      - db
    depends_on:
      - db

  # Startup
  # script:
  #   container_name: script
  #   external_links:
  #     - api
  #   depends_on:
  #     - api
