FROM node:16.15.1

ENV NODE_ENV=development

WORKDIR /app

COPY ["package.json", "package-lock.json*", "tsconfig.json", "./"]

COPY . .

RUN ls -a && npm install

EXPOSE 8080

# TODO: Normally this should not wipe the db but needs verifying
ENTRYPOINT ["sh", "-c", "npm run migrate:dev && npm run dev"]
